### ISSUE TITLE
CMake Error at FindRBDL.cmake:245 (MESSAGE):    Could not find RBDL. trying to run the 'simple' example.

### ISSUE THREAD

**Issue by xiao-wang007** [rbdl/rbdl#75]
Hi there

I am pretty unfamiliar with cmake. Need your help here! 
When I do ```cmake ../``` in build folder in ```example/simple/build```, it gives the error could not find RBDL.

My source dir is ```/home/xiao/rbdl ```.  My build dir is ``` /home/xiao/rbdl-build ```.

How to set ```CUSTOM_RBDL_PATH in FindRBDL.cmake``` ?  I tried use set in this .cmake to point to the directory above. None of it worked. 

Thanks in advance!

**Comment by ju6ge** [comment]
I would suggest you use "ccmake" it is a more interactive way of using "cmake" with which you can set variables and activate build features more easily. You should also read up on "cmake" there are a ton of resources on the internet that will help you understand what you are doing.

**Comment by xiao-wang007** [comment]
> Hi thanks for the advice!
I tried using ```ccmake ../``` in ``` ~/rbdl/examples/simple/build```. It indeed pop out to let me set the variable, but what should I set it to? What is the path to find RBDL?  
Can you please give me some details on this?

Cheers!

**Comment by xiao-wang007** [comment]
Hi thanks for the advice!
I tried using ccmake ../ in  ~/rbdl/examples/simple/build. It indeed pop out to let me set the variable, but what should I set it to? What is the path to find RBDL?
Can you please give me some details on this?

cheers!

**Comment by xiao-wang007** [comment]
> I would suggest you use "ccmake" it is a more interactive way of using "cmake" with which you can set variables and activate build features more easily. You should also read up on "cmake" there are a ton of resources on the internet that will help you understand what you are doing.


Hi thanks for the advice!
I tried using ccmake ../ in ~/rbdl/examples/simple/build. It indeed pop out to let me set the variable, but what should I set it to? What is the path to find RBDL?
Can you please give me some details on this?

cheers!

**Comment by ju6ge** [comment]
The reason I said there are tons of resources is that you asked how to set variables that is something to look up, not bother maintainers with. My time is constrained and helping people learning how to use a build system is not what i am paid for. 

Also I can not tell you what you need to set the variable to, that depends on your system and how you configured the build. Which is why you need to lean how to use `cmake`. It is fine to be a beginner just do not expect people to do your work for you. Also do not open multiple issues on the same topic, that is just rude and not what the issues are for. 

If I had to guess, you are missing a step in the build process. Probably you forgot to run `make install` to install the library system wide.

**Comment by xiao-wang007** [comment]
Thanks for that! You are right! I did missed to ```make install```. Thanks for your time!
