### ISSUE TITLE
How to add a spring force?

### ISSUE THREAD

**Issue by iportolesrb** [rbdl/rbdl#80]
Hi,

I have a model with loop constraints and I need to add a spring to a non-actuated joint. I am using InverseDynamicsConstraints(). Is there any way to do it? 

Thanks.

**Comment by mjhmilla** [comment]
Dear @iportolesrb 

You can include the spring force as an external force by passing in f_ext argument. The f_ext is only briefly described in the doxygen. To add some extra detail:

- f_ext is vector of spatial vectors, with one spatial vector per body.
- Each spatial vector contains the wrench that the external force/torque applies to the body
- Now for the slightly odd part (unless you've read Featherstone's book): the wrench must be calculated with respect to the inertial frame and described in the coordinates of the inertial frame.

You can see an example of using the f_ext argument to apply external forces to the foot of a human walking model here: near line 149 of examples/walkingInverseDynamicsWithPython/processInverseDynamics.py. The code that converts the forces measured by a force plate into the wrenches needed in f_ext is between lines 121-147.

Since you have a spring that is between two bodies, you will have to set two entries in f_ext so that the spring applies an equal and opposite force to each body. Once you have the wrench evaluated, you can use the function GetBodyId to get the index within f_ext associated with a specific body (see line 114-115 of processInverseDynamics.py)

Best wishes,

@mjhmilla

**Comment by iportolesrb** [comment]
Hi @mjhmilla 
It was really helpful, thank you, the example is very clear.
